title: Schema
description: Identifiable ODCS description of a schema
allOf:
  - $ref: "AbstractSchema.yaml"
  - type: object
    properties:
      _id:
        type: string
      properties:
        type: array
        items:
          $ref: "Property.yaml"
    required: [name, _id]
