// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *DataContractCreate) setDefaults() {
	{
		val := DataContractCreateApiVersion("v3.0.0")
		s.ApiVersion = val
	}
	{
		val := DataContractCreateKind("DataContract")
		s.Kind = val
	}
}

// setDefaults set default value of fields.
func (s *DataContractDataContract) setDefaults() {
	{
		val := DataContractDataContractApiVersion("v3.0.0")
		s.ApiVersion = val
	}
	{
		val := DataContractDataContractKind("DataContract")
		s.Kind = val
	}
}

// setDefaults set default value of fields.
func (s *DataContractUpdate) setDefaults() {
	{
		val := DataContractUpdateApiVersion("v3.0.0")
		s.ApiVersion.SetTo(val)
	}
	{
		val := DataContractUpdateKind("DataContract")
		s.Kind.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DataQualityLibrary) setDefaults() {
	{
		val := DataQualityLibraryType("library")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DataQualitySql) setDefaults() {
	{
		val := DataQualitySqlType("library")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *NotFoundError) setDefaults() {
	{
		val := string("Document not found")
		s.ErrorMessage = val
	}
}
