// Code generated by ogen, DO NOT EDIT.
package api

type CreateCollaborationSpaceRes interface {
	createCollaborationSpaceRes()
}

type CreateCollaboratorRes interface {
	createCollaboratorRes()
}

type CreateDataContractReq interface {
	createDataContractReq()
}

type CreateDataContractRes interface {
	createDataContractRes()
}

type CreatePropertyRes interface {
	createPropertyRes()
}

type CreateSchemaRes interface {
	createSchemaRes()
}

type DeleteCageRes interface {
	deleteCageRes()
}

type DeleteCollaborationSpaceRes interface {
	deleteCollaborationSpaceRes()
}

type DeleteCollaboratorRes interface {
	deleteCollaboratorRes()
}

type DeleteDataContractRes interface {
	deleteDataContractRes()
}

type DeleteInviteRes interface {
	deleteInviteRes()
}

type DeletePropertyRes interface {
	deletePropertyRes()
}

type DeleteSchemaRes interface {
	deleteSchemaRes()
}

type DeployCageRes interface {
	deployCageRes()
}

type GetAlgorithmLogsRes interface {
	getAlgorithmLogsRes()
}

type GetAttestationReportRes interface {
	getAttestationReportRes()
}

type GetClientRes interface {
	getClientRes()
}

type GetCollaborationSpaceAppIdRes interface {
	getCollaborationSpaceAppIdRes()
}

type GetCollaborationSpaceRes interface {
	getCollaborationSpaceRes()
}

type GetCollaborationSpaceWebIdRes interface {
	getCollaborationSpaceWebIdRes()
}

type GetCollaborationSpacesRes interface {
	getCollaborationSpacesRes()
}

type GetCollaboratorRes interface {
	getCollaboratorRes()
}

type GetCollaboratorsRes interface {
	getCollaboratorsRes()
}

type GetDataContractRes interface {
	getDataContractRes()
}

type GetDataContractsRes interface {
	getDataContractsRes()
}

type GetDeploymentLogsRes interface {
	getDeploymentLogsRes()
}

type GetDeploymentRes interface {
	getDeploymentRes()
}

type GetInvitesRes interface {
	getInvitesRes()
}

type GetNotificationsRes interface {
	getNotificationsRes()
}

type GetPropertyRes interface {
	getPropertyRes()
}

type GetPublicClientRes interface {
	getPublicClientRes()
}

type GetPublicKeyRes interface {
	getPublicKeyRes()
}

type GetSchemaRes interface {
	getSchemaRes()
}

type PublishEventRes interface {
	publishEventRes()
}

type RotateKeysRes interface {
	rotateKeysRes()
}

type StoreSecretRes interface {
	storeSecretRes()
}

type UpdateCollaborationSpaceRes interface {
	updateCollaborationSpaceRes()
}

type UpdateCollaboratorRes interface {
	updateCollaboratorRes()
}

type UpdateDataContractRes interface {
	updateDataContractRes()
}

type UpdateInviteRes interface {
	updateInviteRes()
}

type UpdateInviteStatusRes interface {
	updateInviteStatusRes()
}

type UpdatePropertyRes interface {
	updatePropertyRes()
}

type UpdateSchemaRes interface {
	updateSchemaRes()
}
