// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	CollaborationSpacesHandler
}

// CollaborationSpacesHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: CollaborationSpaces
type CollaborationSpacesHandler interface {
	// GetCollaborators implements GetCollaborators operation.
	//
	// Get all collaborators of a collaboration space. Allowed if the client owns it or is a collaborator.
	//
	// GET /collaborators
	GetCollaborators(ctx context.Context) (GetCollaboratorsRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
