// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *NotFoundError) setDefaults() {
	{
		val := string("Document not found")
		s.ErrorMessage = val
	}
}
