// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetCollaborators implements GetCollaborators operation.
//
// Get all collaborators of a collaboration space. Allowed if the client owns it or is a collaborator.
//
// GET /collaborators
func (UnimplementedHandler) GetCollaborators(ctx context.Context) (r GetCollaboratorsRes, _ error) {
	return r, ht.ErrNotImplemented
}
