// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/go-faster/errors"
)

func (s GetCollaboratorsOKApplicationJSON) Validate() error {
	alias := ([]Collaborator)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}
